Repository AY2223S2-CS2103T-T15-4/tp, pull requests merged in 2023-03, with the labels that each got.

#79 Update AboutUs and DG
  docs/AboutUs.md
  docs/DeveloperGuide.md
Labels: documentation

#76 Update README and User Guide
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findAlexYuResult.png
Labels: documentation

#81 Add Module Command
  docs/AboutUs.md
  docs/UserGuide.md
  src/main/java/tfifteenfour/clipboard/logic/commands/EditCommand.java
  src/main/java/tfifteenfour/clipboard/logic/commands/ModuleCommand.java
  src/main/java/tfifteenfour/clipboard/logic/parser/AddCommandParser.java
  src/main/java/tfifteenfour/clipboard/logic/parser/EditCommandParser.java
  src/main/java/tfifteenfour/clipboard/logic/parser/ModuleCommandParser.java
  src/main/java/tfifteenfour/clipboard/logic/parser/ParserUtil.java
  src/main/java/tfifteenfour/clipboard/logic/parser/RosterParser.java
  src/main/java/tfifteenfour/clipboard/model/student/Course.java
  src/main/java/tfifteenfour/clipboard/model/student/Student.java
  src/main/java/tfifteenfour/clipboard/model/student/StudentTakingModulePredicate.java
  src/main/java/tfifteenfour/clipboard/model/util/SampleDataUtil.java
  src/main/java/tfifteenfour/clipboard/storage/JsonAdaptedModuleCode.java
  src/main/java/tfifteenfour/clipboard/storage/JsonAdaptedStudent.java
  src/test/java/tfifteenfour/clipboard/logic/commands/ModuleCommandTest.java
  src/test/java/tfifteenfour/clipboard/logic/parser/AddCommandParserTest.java
  src/test/java/tfifteenfour/clipboard/logic/parser/EditCommandParserTest.java
  src/test/java/tfifteenfour/clipboard/logic/parser/ModuleCommandParserTest.java
  src/test/java/tfifteenfour/clipboard/model/student/ModuleCodeTest.java
  src/test/java/tfifteenfour/clipboard/model/student/StudentTakingModulePredicateTest.java
  src/test/java/tfifteenfour/clipboard/testutil/EditStudentDescriptorBuilder.java
  src/test/java/tfifteenfour/clipboard/testutil/StudentBuilder.java
  src/test/java/tfifteenfour/clipboard/testutil/StudentUtil.java
Labels: priority.Medium

#114 Allows user to mark attendance of students
  src/main/java/tfifteenfour/clipboard/commons/core/Messages.java
  src/main/java/tfifteenfour/clipboard/logic/CurrentSelection.java
  src/main/java/tfifteenfour/clipboard/logic/commands/BackCommand.java
  src/main/java/tfifteenfour/clipboard/logic/commands/SelectCommand.java
  src/main/java/tfifteenfour/clipboard/logic/commands/addcommand/AddSessionCommand.java
  src/main/java/tfifteenfour/clipboard/logic/commands/attendancecommand/AttendanceCommand.java
  src/main/java/tfifteenfour/clipboard/logic/commands/attendancecommand/MarkAbsentCommand.java
  src/main/java/tfifteenfour/clipboard/logic/commands/attendancecommand/MarkPresentCommand.java
  src/main/java/tfifteenfour/clipboard/logic/commands/deletecommand/DeleteCourseCommand.java
  src/main/java/tfifteenfour/clipboard/logic/commands/deletecommand/DeleteGroupCommand.java
  src/main/java/tfifteenfour/clipboard/logic/commands/deletecommand/DeleteSessionCommand.java
  src/main/java/tfifteenfour/clipboard/logic/parser/AddCommandParser.java
  src/main/java/tfifteenfour/clipboard/logic/parser/AttendanceCommandParser.java
  src/main/java/tfifteenfour/clipboard/logic/parser/DeleteCommandParser.java
  src/main/java/tfifteenfour/clipboard/logic/parser/MarkCommandParser.java
  src/main/java/tfifteenfour/clipboard/logic/parser/ParserUtil.java
  src/main/java/tfifteenfour/clipboard/logic/parser/RosterParser.java
  src/main/java/tfifteenfour/clipboard/logic/parser/UnmarkCommandParser.java
  src/main/java/tfifteenfour/clipboard/model/course/Course.java
  src/main/java/tfifteenfour/clipboard/model/course/Group.java
  src/main/java/tfifteenfour/clipboard/model/course/Session.java
  src/main/java/tfifteenfour/clipboard/model/course/UniqueSessionsList.java
  src/main/java/tfifteenfour/clipboard/model/course/exceptions/CourseNotFoundException.java
  src/main/java/tfifteenfour/clipboard/model/course/exceptions/DuplicateGroupException.java
  src/main/java/tfifteenfour/clipboard/model/course/exceptions/DuplicateSessionException.java
  src/main/java/tfifteenfour/clipboard/model/course/exceptions/GroupNotFoundException.java
  src/main/java/tfifteenfour/clipboard/model/course/exceptions/SessionNotFoundException.java
  src/main/java/tfifteenfour/clipboard/model/course/exceptions/StudentNotInSessionException.java
  src/main/java/tfifteenfour/clipboard/model/student/Session.java
  src/main/java/tfifteenfour/clipboard/storage/JsonAdaptedGroup.java
  src/main/java/tfifteenfour/clipboard/storage/JsonAdaptedSession.java
  src/main/java/tfifteenfour/clipboard/storage/serializedclasses/SerializedGroup.java
  src/main/java/tfifteenfour/clipboard/storage/serializedclasses/SerializedRoster.java
  src/main/java/tfifteenfour/clipboard/storage/serializedclasses/SerializedSession.java
Labels: type.Story, priority.High

#131 Add CLIppy mascot animation GIFs to images folder
  docs/images/CommandFail.GIF
  docs/images/CommandSuccess.GIF
Labels: UI

#133 Implement Task and Assign Functionality
  src/main/java/tfifteenfour/clipboard/commons/core/Messages.java
  src/main/java/tfifteenfour/clipboard/logic/CurrentSelection.java
  src/main/java/tfifteenfour/clipboard/logic/PageType.java
  src/main/java/tfifteenfour/clipboard/logic/commands/BackCommand.java
  src/main/java/tfifteenfour/clipboard/logic/commands/SelectCommand.java
  src/main/java/tfifteenfour/clipboard/logic/commands/addcommand/AddTaskCommand.java
  src/main/java/tfifteenfour/clipboard/logic/commands/deletecommand/DeleteTaskCommand.java
  src/main/java/tfifteenfour/clipboard/logic/commands/editcommand/EditStudentCommand.java
  src/main/java/tfifteenfour/clipboard/logic/commands/editcommand/EditTaskCommand.java
  src/main/java/tfifteenfour/clipboard/logic/commands/taskcommand/AssignCommand.java
  src/main/java/tfifteenfour/clipboard/logic/commands/taskcommand/TaskCommand.java
  src/main/java/tfifteenfour/clipboard/logic/parser/AddCommandParser.java
  src/main/java/tfifteenfour/clipboard/logic/parser/AssignCommandParser.java
  src/main/java/tfifteenfour/clipboard/logic/parser/CommandTargetType.java
  src/main/java/tfifteenfour/clipboard/logic/parser/DeleteCommandParser.java
  src/main/java/tfifteenfour/clipboard/logic/parser/ParserUtil.java
  src/main/java/tfifteenfour/clipboard/logic/parser/RosterParser.java
  src/main/java/tfifteenfour/clipboard/logic/parser/TaskCommandParser.java
  src/main/java/tfifteenfour/clipboard/model/course/Group.java
  src/main/java/tfifteenfour/clipboard/model/student/StudentWithGrades.java
  src/main/java/tfifteenfour/clipboard/model/task/Task.java
  src/main/java/tfifteenfour/clipboard/model/task/UniqueTasksList.java
  src/main/java/tfifteenfour/clipboard/model/task/exceptions/DuplicateTaskException.java
  src/main/java/tfifteenfour/clipboard/model/task/exceptions/StudentNotInPageException.java
  src/main/java/tfifteenfour/clipboard/model/task/exceptions/TaskNotFoundException.java
  src/main/java/tfifteenfour/clipboard/storage/serializedclasses/SerializedGroup.java
  src/main/java/tfifteenfour/clipboard/storage/serializedclasses/SerializedTask.java
Labels: priority.High

#128 Update User Guide with changes from re-modelling
  docs/UserGuide.md
  docs/images/UiAttendance.png
  docs/images/UiCoursePage.png
  docs/images/UiGroupPage.png
  docs/images/UiStudentPage.png
  docs/images/UpdatedUi.png
  docs/images/navigation.png
Labels: documentation

#142 Update edit task command
  src/main/java/tfifteenfour/clipboard/logic/parser/NewEditCommandParser.java
Labels: type.Bug

#141 Update User Guide with Task commands and other updates
  docs/UserGuide.md
  docs/images/UiAttendance.png
  docs/images/UiCoursePage.png
  docs/images/UiGroupPage.png
  docs/images/UiStudentPage.png
  docs/images/UpdatedUI.png
  docs/images/UpdatedUi.png
  docs/images/navigation.png
Labels: documentation

#143 Fix bugs in `edit student`
  src/main/java/tfifteenfour/clipboard/logic/commands/Command.java
  src/main/java/tfifteenfour/clipboard/logic/commands/editcommand/EditStudentCommand.java
  src/main/java/tfifteenfour/clipboard/logic/parser/NewEditCommandParser.java
  src/main/java/tfifteenfour/clipboard/logic/parser/Parser.java
  src/main/java/tfifteenfour/clipboard/logic/parser/RosterParser.java
Labels: type.Bug

#150 Fixed command help prompt for `add student`
  src/main/java/tfifteenfour/clipboard/logic/commands/addcommand/AddStudentCommand.java
Labels: type.Bug

#157 Fix runtime error of attendance
  src/main/java/tfifteenfour/clipboard/logic/commands/attendancecommand/AttendanceCommand.java
Labels: type.Bug
